[template]
ignore = [
    "target",
    ".git",
]
exclude = [
    "android/app/src/main/res/mipmap-*/",
    "android/gradle/wrapper/gradle-wrapper.jar",
]

[hooks]
pre = ["scripts/android.rhai", "scripts/more_vars.rhai"]
ignore = ["target", ".git"]
